### PR TITLE
Use null_deleter from Boost.Core instead of own definition

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by mclow** [comment]
I think that this is a tossup.
On one hand, it removes a (small) class from Boost.UUID.
On the other hand, it adds a dependency on Boost.Core.
On the gripping hand, most everything in boost already depends on Boost.Core.

**Comment by tklauser** [comment]
boost/uuid/seed_rng.hpp already has a dependency on a header from Boost.Core (boost/core/noncopyable.hpp), so I thought it should be fine add another dependency. I probably should have mentioned this in the PR, sorry.

**Comment by mclow** [comment]
Please keep an eye on the test bots, and ping me in a week or so to merge to master.

**Comment by tklauser** [comment]
Will do. Thanks!

**Comment by tklauser** [comment]
@mclow pinging for merge to master. The test bots didn't show any failure which I could trace to this change.

**Comment by tklauser** [comment]
@mclow pinging again for merge to master

**Comment by mclow** [comment]
This has been done for the 1.64.0 release.

**Pull request merged**
