### PR TITLE
uuid::data_type: make operator() constexpr

### PR DESCRIPTION
**Pull request by rressi-at-globus**

### CODE REVIEW

**Comment by pdimov** [comment]
These are already `constexpr` on `develop` and `master` and should be in 1.87 (currently [beta RC2](https://lists.boost.org/Archives/boost/2024/11/258261.php)).

**Comment by jeking3** [comment]
If that's true, why is there a delta in this PR on boostorg/develop, which is the staging area for things going into releases?

**Comment by pdimov** [comment]
It's probably been created from a stale develop.

**Comment by jeking3** [comment]
Makes sense, forgot about that :)

**Comment by jeking3** [comment]
Double-checked, agree, closing.

**Pull request closed without merging**
