### PR TITLE
Drone config

### PR DESCRIPTION
**Pull request by sdarwin**
Drone is a continuous integration framework similar to Travis CI. [The C++ Alliance](https://cppalliance.org/) is offering a hosted Drone server for Boost libraries. Please refer to https://github.com/CPPAlliance/drone-ci for more information and instructions.

### CODE REVIEW

**Comment by jeking3** [comment]
I'm confused; are we using drone or GitHub Actions going forward?  I see PRs for both.

**Comment by sdarwin** [comment]
Your decision.  You are welcome to use both, which can provide redundancy and more test coverage.  Sometimes, one of the systems will be slow when the other is fast, so you get faster results.

**Comment by jeking3** [comment]
I've been away for a good long time due to startups (and just peeking in to see what I need to do for the 1.77 release)... this repo uses Travis CI and Appveyor through boost-ci.  That repo was an attempt to standardize testing throughout boost and it ended up with some adoption.  Rolling out updates was always a problem however as it required individual attention to each repository using it.

Is there a general consensus about which system the project is moving towards?

I'd prefer to see each of these actually run in CI before I merge anything.  I wouldn't mind switching to GitHub Actions at some point.  Not sure if they support different endianness yet, which is important for testing this library.

**Comment by sdarwin** [comment]
> I'd prefer to see each of these actually run in CI before I merge anything.

In that case, you might copy the files into a fork in your own github account, and test.

**Pull request closed without merging**
